"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

const MAX_BYTES=100*1024*1024;
const allowed=["video/mp4","video/quicktime","video/webm"];
const manualExercises=[
  {value:"squat",label:"Squat"},{value:"jumping_jack",label:"Jumping jack"},{value:"push_up",label:"Push-up"},
  {value:"pull_up",label:"Pull-up"},{value:"lunge",label:"Lunge"},{value:"sit_up",label:"Sit-up"},
  {value:"mountain_climber",label:"Mountain climber"},{value:"burpee",label:"Burpee"},{value:"plank",label:"Plank (timed)"},
];

export default function UploadPage(){
  const router=useRouter(); const abortRef=useRef<AbortController|null>(null);
  const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<string|null>(null); const [duration,setDuration]=useState<number|null>(null);
  const [weight,setWeight]=useState(""); const [mode,setMode]=useState<"auto"|"manual">("auto"); const [manualExercise,setManualExercise]=useState("squat");
  const [phase,setPhase]=useState<"idle"|"checking"|"uploading"|"starting">("idle"); const [error,setError]=useState<string|null>(null); const busy=phase!=="idle";
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);

  function choose(next:File|null){
    setError(null); setDuration(null); if(preview)URL.revokeObjectURL(preview); setPreview(null);
    setFile(null); if(!next){return} if(!allowed.includes(next.type)){setError("Choose an MP4, MOV, or WebM file.");return} if(next.size>MAX_BYTES){setError("Video must be smaller than 100 MB.");return}
    const url=URL.createObjectURL(next); const video=document.createElement("video"); video.preload="metadata"; video.onloadedmetadata=()=>{if(video.duration>180||video.duration<=0){setError("Video must be between 1 second and 3 minutes.");URL.revokeObjectURL(url);return}setFile(next);setPreview(url);setDuration(video.duration)}; video.onerror=()=>{setError("This video could not be read.");URL.revokeObjectURL(url)}; video.src=url;
  }
  async function submit(event:React.FormEvent){event.preventDefault();setError(null);const kg=Number(weight);if(!file)return setError("Choose a workout video first.");if(!Number.isFinite(kg)||kg<30||kg>250)return setError("Enter a body weight between 30 and 250 kg.");const controller=new AbortController();abortRef.current=controller;
    try{setPhase("checking");const prepared=await fetch("/api/upload-url",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contentType:file.type,size:file.size}),signal:controller.signal});const upload=await prepared.json();if(!prepared.ok)throw new Error(upload.error??"Could not prepare upload.");setPhase("uploading");const sent=await fetch(upload.uploadUrl,{method:"PUT",headers:{"Content-Type":file.type},body:file,signal:controller.signal});if(!sent.ok)throw new Error("Video upload failed.");setPhase("starting");const created=await fetch("/api/create-job",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({videoKey:upload.key,uploadToken:upload.uploadToken,weightKg:kg,exercise:mode==="auto"?"auto":manualExercise}),signal:controller.signal});const job=await created.json();if(!created.ok)throw new Error(job.error??"Could not start analysis.");router.push(`/results/${job.jobId}?token=${job.accessToken}`)}catch(reason){setError(reason instanceof DOMException&&reason.name==="AbortError"?"Upload cancelled.":reason instanceof Error?reason.message:"Something went wrong.");setPhase("idle")}}
  return <main className="min-h-screen bg-[var(--paper)]"><header className="shell site-header"><Link href="/" className="brand"><span className="brand-mark">C</span>cALorie</Link><span className="font-mono text-[10px] font-bold tracking-[.12em] text-[var(--muted)]">New analysis</span></header>
    <form onSubmit={submit} className="upload-form shell grid min-h-[calc(100vh-80px)] lg:grid-cols-[1.55fr_.85fr]">
      <section className="py-10 lg:border-r lg:border-[var(--line)] lg:pr-12"><p className="eyebrow">01 / Add video</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Your workout starts here.</h1><p className="mt-3 text-sm text-[var(--muted)]">One person · steady camera · working joints visible</p>
        <label htmlFor="video" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0]??null)}} className="upload-drop mt-8 grid min-h-72 cursor-pointer place-items-center border border-dashed border-[#454c46] bg-[var(--surface)] p-8 text-center transition hover:border-[var(--signal)]"><input id="video" className="sr-only" type="file" accept="video/mp4,video/quicktime,video/webm" onChange={e=>choose(e.target.files?.[0]??null)}/><span><i className="upload-icon mx-auto grid h-16 w-16 place-items-center bg-[var(--signal)] text-3xl not-italic text-[#0c0e0d]">↑</i><b className="mt-5 block text-sm  tracking-wider">Drop your workout here</b><span className="helper mt-2 block">MP4, MOV or WebM · up to 100 MB · 3 min max</span></span></label>
        {preview?<div className="mt-5"><video className="aspect-video w-full bg-black object-contain" src={preview} controls preload="metadata"/><div className="mt-3 flex flex-wrap justify-between gap-2 text-xs"><b className="max-w-[70%] truncate">{file?.name}</b><span className="text-[var(--muted)]">{(file!.size/1024/1024).toFixed(1)} MB · {duration?.toFixed(1)} sec</span></div></div>:null}
        <div className="mt-7 grid grid-cols-2 border-y border-[var(--line)] text-[10px] font-bold tracking-wider text-[var(--muted)] sm:grid-cols-4">{["Full body","Stable camera","Even light","One person"].map((item,index)=><span className="border-[var(--line)] px-4 py-5 sm:border-r" key={item}><i className="mr-2 not-italic text-[var(--signal)]">0{index+1}</i>{item.toUpperCase()}</span>)}</div>
      </section>
      <aside className="setup-panel bg-[var(--surface)] px-0 py-10 lg:px-10"><p className="eyebrow">02 / Analysis setup</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em]">A few details.</h2><div className="mt-8"><label htmlFor="weight" className="label">Body weight (kg)</label><input id="weight" className="input" type="number" min="30" max="250" step="0.1" placeholder="70" value={weight} onChange={e=>setWeight(e.target.value)}/><p className="helper mt-2">Used only in the MET calculation.</p></div>
        <fieldset className="mt-8"><legend className="label">Analysis mode</legend><label className={`mode-option flex cursor-pointer gap-3 border p-4 ${mode==="auto"?"border-[var(--signal)]":"border-[var(--line)]"}`}><input className="accent-[var(--signal)]" type="radio" checked={mode==="auto"} onChange={()=>setMode("auto")}/><span><b className="block text-xs  tracking-wide">Automatic mixed workout</b><span className="helper">Separates supported exercises, rest and unknown periods.</span></span></label><label className={`mt-3 mode-option flex cursor-pointer gap-3 border p-4 ${mode==="manual"?"border-[var(--signal)]":"border-[var(--line)]"}`}><input className="accent-[var(--signal)]" type="radio" checked={mode==="manual"} onChange={()=>setMode("manual")}/><span><b className="block text-xs  tracking-wide">Manual single exercise</b><span className="helper">Use when the full video contains one known movement.</span></span></label></fieldset>
        {mode==="manual"&&<div className="mt-5"><label className="label" htmlFor="exercise">Exercise override</label><select id="exercise" className="input" value={manualExercise} onChange={e=>setManualExercise(e.target.value)}>{manualExercises.map(item=><option value={item.value} key={item.value}>{item.label}</option>)}</select></div>}
        <details className="mt-7 border-y border-[var(--line)] py-4"><summary className="cursor-pointer text-xs font-bold  tracking-wide">9 supported movements & camera guide</summary><p className="mt-4 text-xs leading-5 text-[var(--muted)]">Front view: jumping jack, lunge, mountain climber. Side view: squat, push-up, sit-up, burpee and plank. Pull-up: full body with hands and bar area visible.</p></details>
        {error&&<p role="alert" className="error mt-6">{error}</p>}{busy&&<div className="mt-6" role="status"><div className="flex justify-between text-xs font-bold"><span>{phase==="checking"?"Preparing":phase==="uploading"?"Uploading":"Starting analysis"}</span><span>{phase==="checking"?"25%":phase==="uploading"?"65%":"100%"}</span></div><div className="mt-2 h-1 bg-[var(--line)]"><div className={`h-full bg-[var(--signal)] ${phase==="checking"?"w-1/4":phase==="uploading"?"w-2/3":"w-full"}`}/></div></div>}
        <div className="mt-7 flex gap-2"><button className="button flex-1" type="submit" disabled={busy}>{busy?"Working…":"Analyze video →"}</button>{busy&&<button className="button secondary" type="button" onClick={()=>abortRef.current?.abort()}>Cancel</button>}</div><p className="helper mt-4">Activity estimate, not a medical measurement.</p>
      </aside>
    </form>
  </main>;
}
