MIN_VISIBILITY = 0.55
MOTION_IDLE_THRESHOLD = 0.006
JOINT_VELOCITY_ACTIVE_THRESHOLD = 2.0
MIN_LABEL_SCORE = 0.55
SMOOTHING_WINDOW_SECONDS = 0.7
MIN_SEGMENT_SECONDS = 1.0
MERGE_GAP_SECONDS = 0.8
MISSING_POSE_GRACE_SECONDS = 0.5

