import Link from "next/link";

const exercises=[["09","Movements","Squat, push-up, pull-up, lunge, sit-up, jumping jack, mountain climber, burpee and plank.","text-[#bbf236]"],["01","Mixed video","Automatic segmentation across sets and rest.","text-[#f36c3d]"],["33","Landmarks","MediaPipe joint geometry measured over time.","text-[#36a4d5]"],["→","Explainable","No black-box calorie number.","text-white"]];

export default function Home(){return <main className="min-h-screen bg-[#0c0e0d] text-[#f5f6ed]">
  <header className="shell site-header"><Link href="/" className="brand"><span className="brand-mark">C</span>cALorie</Link><div className="flex items-center gap-6"><span className="hidden font-mono text-[10px] tracking-[.12em] text-[#8d958f] sm:block">MOVEMENT INTELLIGENCE</span><Link href="/upload" className="text-xs font-bold uppercase tracking-wider no-underline">Analyze ↗</Link></div></header>
  <section className="shell grid gap-12 py-10 lg:grid-cols-[1.35fr_.85fr] lg:items-center lg:py-14"><div className="max-w-3xl"><p className="eyebrow">Pose-based workout analysis</p><h1 className="mt-6 text-[clamp(3.6rem,7.4vw,7rem)] font-black leading-[.84] tracking-[-.075em]">Your workout,<br/><span className="text-[#bbf236]">cut into truth.</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-[#a0a7a1] sm:text-lg">Upload one mixed workout. cALorie maps every set, counts complete repetitions and shows exactly how the estimate was made.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/upload" className="button">Analyze a workout ↗</Link><a href="#method" className="button secondary">See the method</a></div></div>
    <aside className="performance-panel p-7 sm:p-9"><div className="flex justify-between font-mono text-[10px] tracking-wider text-[#8d958f]"><span>LIVE BREAKDOWN</span><span>01:24</span></div><div className="mt-7 flex items-end gap-3"><strong className="text-8xl font-black leading-none tracking-[-.08em]">38</strong><span className="mb-2 text-xs font-bold text-[#bbf236]">TOTAL REPS</span></div><div className="mt-9 flex h-11 gap-1 border border-[#30362f] p-1" aria-label="Example activity timeline"><span className="w-[30%] bg-[#bbf236]"/><span className="w-[11%] bg-[#444a45]"/><span className="w-[26%] bg-[#f36c3d]"/><span className="w-[33%] bg-[#36a4d5]"/></div><p className="mt-4 text-xs font-bold">Squat 12&nbsp; · &nbsp;Push-up 8&nbsp; · &nbsp;Jumping jack 18</p><p className="mt-2 text-[11px] text-[#8d958f]">Rule-based segmentation · 91% pose coverage</p></aside></section>
  <section id="method" className="shell grid border-y border-[#30362f] md:grid-cols-4">{exercises.map(([n,title,copy,color],index)=><article className={`min-h-48 py-7 md:px-6 ${index?"border-t border-[#30362f] md:border-l md:border-t-0":""}`} key={title}><span className={`text-xs font-black ${color}`}>{n}</span><h2 className="mt-7 text-lg font-black uppercase tracking-[-.02em]">{title}</h2><p className="mt-3 text-xs leading-5 text-[#8d958f]">{copy}</p></article>)}</section>
  <footer className="shell flex flex-wrap justify-between gap-3 py-7 font-mono text-[10px] tracking-wider text-[#747c76]"><span>cALorie / COMPUTER ENGINEERING PROJECT</span><span>ACTIVITY ESTIMATE · NOT A MEDICAL MEASUREMENT</span></footer>
</main>}
